<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ExamQuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('questions')->insert([
            [
                'exam_id' => 1,
                'question_text' => 'What is 2 + 3?',
                'choice1' => '4',
                'choice2' => '5',
                'choice3' => '6',
                'choice4' => '7',
                'correct_choice' => 'choice2',
                'mark' => 1,
                'description' => 'Basic addition question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 1,
                'question_text' => 'What is the square root of 16?',
                'choice1' => '2',
                'choice2' => '4',
                'choice3' => '8',
                'choice4' => '16',
                'correct_choice' => 'choice2',
                'mark' => 1,
                'description' => 'Basic square root question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 1,
                'question_text' => 'What is 5 * 5?',
                'choice1' => '15',
                'choice2' => '20',
                'choice3' => '25',
                'choice4' => '30',
                'correct_choice' => 'choice3',
                'mark' => 1,
                'description' => 'Basic multiplication question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 1,
                'question_text' => 'What is 10 / 2?',
                'choice1' => '3',
                'choice2' => '4',
                'choice3' => '5',
                'choice4' => '6',
                'correct_choice' => 'choice3',
                'mark' => 1,
                'description' => 'Basic division question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 1,
                'question_text' => 'What is the value of pi (π)?',
                'choice1' => '3.14',
                'choice2' => '3.1416',
                'choice3' => '3.14159',
                'choice4' => '3.141592',
                'correct_choice' => 'choice3',
                'mark' => 1,
                'description' => 'Mathematical constant question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'Who is the President of the United States?',
                'choice1' => 'Barack Obama',
                'choice2' => 'Donald Trump',
                'choice3' => 'Joe Biden',
                'choice4' => 'George Washington',
                'correct_choice' => 'choice3',
                'mark' => 1,
                'description' => 'Current President of the United States',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'Who is the President of the United States?',
                'choice1' => 'Barack Obama',
                'choice2' => 'Donald Trump',
                'choice3' => 'Joe Biden',
                'choice4' => 'George Washington',
                'correct_choice' => 'choice3',
                'mark' => 1,
                'description' => 'Current President of the United States',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'What is the capital of France?',
                'choice1' => 'Paris',
                'choice2' => 'Berlin',
                'choice3' => 'London',
                'choice4' => 'Madrid',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Capital city of France',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'What is the capital of Germany?',
                'choice1' => 'Paris',
                'choice2' => 'Berlin',
                'choice3' => 'London',
                'choice4' => 'Madrid',
                'correct_choice' => 'choice2',
                'mark' => 1,
                'description' => 'Capital city of Germany',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'What is the largest ocean on Earth?',
                'choice1' => 'Atlantic Ocean',
                'choice2' => 'Indian Ocean',
                'choice3' => 'Arctic Ocean',
                'choice4' => 'Pacific Ocean',
                'correct_choice' => 'choice4',
                'mark' => 1,
                'description' => 'Geography question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'Who wrote the play "Romeo and Juliet"?',
                'choice1' => 'William Shakespeare',
                'choice2' => 'Charles Dickens',
                'choice3' => 'Jane Austen',
                'choice4' => 'Mark Twain',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Literature question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'What is the chemical symbol for water?',
                'choice1' => 'H',
                'choice2' => 'O',
                'choice3' => 'W',
                'choice4' => 'H2O',
                'correct_choice' => 'choice4',
                'mark' => 1,
                'description' => 'Chemistry question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'Who painted the Mona Lisa?',
                'choice1' => 'Leonardo da Vinci',
                'choice2' => 'Vincent van Gogh',
                'choice3' => 'Pablo Picasso',
                'choice4' => 'Michelangelo',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Art question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'What is the capital of Japan?',
                'choice1' => 'Beijing',
                'choice2' => 'Tokyo',
                'choice3' => 'Seoul',
                'choice4' => 'Bangkok',
                'correct_choice' => 'choice2',
                'mark' => 1,
                'description' => 'Capital city of Japan',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'What is the currency of India?',
                'choice1' => 'Rupee',
                'choice2' => 'Rupiah',
                'choice3' => 'Dollar',
                'choice4' => 'Yen',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Currency question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 2,
                'question_text' => 'What is the tallest mountain in the world?',
                'choice1' => 'Mount Kilimanjaro',
                'choice2' => 'Mount Everest',
                'choice3' => 'Mount Fuji',
                'choice4' => 'K2',
                'correct_choice' => 'choice2',
                'mark' => 1,
                'description' => 'Geography question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'What is the capital of France?',
                'choice1' => 'Paris',
                'choice2' => 'Berlin',
                'choice3' => 'London',
                'choice4' => 'Madrid',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Capital city of France',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'Who wrote "To Kill a Mockingbird"?',
                'choice1' => 'Harper Lee',
                'choice2' => 'Mark Twain',
                'choice3' => 'Charles Dickens',
                'choice4' => 'J.K. Rowling',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Literature question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'What is the chemical symbol for water?',
                'choice1' => 'H',
                'choice2' => 'O',
                'choice3' => 'W',
                'choice4' => 'H2O',
                'correct_choice' => 'choice4',
                'mark' => 1,
                'description' => 'Chemistry question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'Who invented the telephone?',
                'choice1' => 'Alexander Graham Bell',
                'choice2' => 'Thomas Edison',
                'choice3' => 'Nikola Tesla',
                'choice4' => 'Albert Einstein',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Inventors question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'What is the currency of Japan?',
                'choice1' => 'Yen',
                'choice2' => 'Dollar',
                'choice3' => 'Euro',
                'choice4' => 'Pound',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Currency question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'Who painted the Mona Lisa?',
                'choice1' => 'Leonardo da Vinci',
                'choice2' => 'Vincent van Gogh',
                'choice3' => 'Pablo Picasso',
                'choice4' => 'Michelangelo',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Art question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'What is the largest planet in the solar system?',
                'choice1' => 'Jupiter',
                'choice2' => 'Saturn',
                'choice3' => 'Earth',
                'choice4' => 'Mars',
                'correct_choice' => 'choice1',
                'mark' => 1,
                'description' => 'Astronomy question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'exam_id' => 3,
                'question_text' => 'Who is credited with discovering the theory of relativity?',
                'choice1' => 'Isaac Newton',
                'choice2' => 'Galileo Galilei',
                'choice3' => 'Albert Einstein',
                'choice4' => 'Stephen Hawking',
                'correct_choice' => 'choice3',
                'mark' => 1,
                'description' => 'Physics question',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

    }
}
